vcom -93 -work ./work ../src/my_package.vhd
vcom -93 -work ./work ../src/MUX21.vhd
vcom -93 -work ./work ../src/MUX31.vhd
vcom -93 -work ./work ../src/MUX41.vhd
vcom -93 -work ./work ../src/Shifter.vhd
vcom -93 -work ./work ../src/Absolute_Value.vhd
vcom -93 -work ./work ../src/Register.vhd
vcom -93 -work ./work ../src/Register_File.vhd
vcom -93 -work ./work ../src/PC_Selector_Contol_Unit.vhd
vcom -93 -work ./work ../src/Immediate_Generation.vhd
vcom -93 -work ./work ../src/Instruction_Encoder.vhd
vcom -93 -work ./work ../src/Hazard_Unit.vhd
vcom -93 -work ./work ../src/Forwarding_Unit.vhd
vcom -93 -work ./work ../src/ALU.vhd
vcom -93 -work ./work ../src/Fetch_Stage.vhd
vcom -93 -work ./work ../src/Decode_Stage.vhd
vcom -93 -work ./work ../src/Execute_Stage.vhd
vcom -93 -work ./work ../src/Branch_Target_Buffer.vhd
vcom -93 -work ./work ../src/Branch_Control_Unit.vhd
vcom -93 -work ./work ../src/Branch_Forwarding_Unit.vhd
vcom -93 -work ./work ../src/Control_Unit.vhd
vcom -93 -work ./work ../src/Execute_Mux_Sel_Encoder.vhd
vcom -93 -work ./work ../src/RISC-V.vhd
vcom -93 -work ./work ../tb/IRAM.vhd
vcom -93 -work ./work ../tb/DRAM.vhd
vcom -93 -work ./work ../tb/tb_RISC_V.vhd

